<a href="https://colab.research.google.com/github/lakshman-reddy-sudo/Phoenixxx-Tv/blob/main/irisDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import numpy as np
iris = np.genfromtxt('iris2.txt', delimiter = ",", dtype=str)
iris

array([['5.1', ' 3.5', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.9', ' 3', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2', ' Iris-setosa', ' 1'],
       ['5', ' 3.6', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4', ' Iris-setosa', ' 1'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3', ' Iris-setosa', ' 1'],
       ['5', ' 3.4', ' 1.5', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1', ' Iris-setosa', ' 1'],
       ['5.5 ', ' 2.6', ' 4.4', ' 1.2', ' Iris-versicolor', ' 2'],
       ['6.1 ', ' 3', ' 4.6', ' 1.4', ' Iris-versicolor', ' 2'],
       ['5.8', ' 2.6', ' 4', ' 1.2', ' Iris-versicolor', ' 2'],
       ['5', ' 2.3', ' 3.3', ' 1', ' Iris-versicolor', ' 2'],
       ['5.6 ', ' 2.7', ' 4.2', ' 1.3', ' Iris-versicolor', ' 2'],
       ['5.7 ', ' 3', ' 4.2', ' 1.2', ' Iris-versicolor', ' 

In [110]:
iris.shape

(30, 6)

In [111]:
iris.ndim

2

In [112]:
iris.size

180

In [113]:
iris = iris[0:30,[0, 1, 2, 3,]]
iris

array([['5.1', ' 3.5', ' 1.4', ' 0.2'],
       ['4.9', ' 3', ' 1.4', ' 0.2'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2'],
       ['5', ' 3.6', ' 1.4', ' 0.2'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3'],
       ['5', ' 3.4', ' 1.5', ' 0.2'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1'],
       ['5.5 ', ' 2.6', ' 4.4', ' 1.2'],
       ['6.1 ', ' 3', ' 4.6', ' 1.4'],
       ['5.8', ' 2.6', ' 4', ' 1.2'],
       ['5', ' 2.3', ' 3.3', ' 1'],
       ['5.6 ', ' 2.7', ' 4.2', ' 1.3'],
       ['5.7 ', ' 3', ' 4.2', ' 1.2'],
       ['5.7', ' 2.9', ' 4.2', ' 1.3'],
       ['6.2 ', ' 2.9', ' 4.3', ' 1.3'],
       ['5.1', ' 2.5', ' 3', ' 1.1'],
       ['5.7', ' 2.8', ' 4.1', ' 1.3'],
       ['6.9', ' 3.1', ' 5.4', ' 2.1'],
       ['6.7', ' 3.1', ' 5.6', ' 2.4'],
       ['6.9', ' 3.1', ' 5.1', ' 2.3'],
       ['5.8', ' 2.7', ' 5.1', ' 1.9'],
       ['6.8', ' 3.2', ' 5.9', ' 2.3'],
       ['6.7

In [114]:
iris1, iris2, iris3 = np.split(iris, [10,20], axis = 0)
iris

array([['5.1', ' 3.5', ' 1.4', ' 0.2'],
       ['4.9', ' 3', ' 1.4', ' 0.2'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2'],
       ['5', ' 3.6', ' 1.4', ' 0.2'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3'],
       ['5', ' 3.4', ' 1.5', ' 0.2'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1'],
       ['5.5 ', ' 2.6', ' 4.4', ' 1.2'],
       ['6.1 ', ' 3', ' 4.6', ' 1.4'],
       ['5.8', ' 2.6', ' 4', ' 1.2'],
       ['5', ' 2.3', ' 3.3', ' 1'],
       ['5.6 ', ' 2.7', ' 4.2', ' 1.3'],
       ['5.7 ', ' 3', ' 4.2', ' 1.2'],
       ['5.7', ' 2.9', ' 4.2', ' 1.3'],
       ['6.2 ', ' 2.9', ' 4.3', ' 1.3'],
       ['5.1', ' 2.5', ' 3', ' 1.1'],
       ['5.7', ' 2.8', ' 4.1', ' 1.3'],
       ['6.9', ' 3.1', ' 5.4', ' 2.1'],
       ['6.7', ' 3.1', ' 5.6', ' 2.4'],
       ['6.9', ' 3.1', ' 5.1', ' 2.3'],
       ['5.8', ' 2.7', ' 5.1', ' 1.9'],
       ['6.8', ' 3.2', ' 5.9', ' 2.3'],
       ['6.7

In [115]:
iris1

array([['5.1', ' 3.5', ' 1.4', ' 0.2'],
       ['4.9', ' 3', ' 1.4', ' 0.2'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2'],
       ['5', ' 3.6', ' 1.4', ' 0.2'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3'],
       ['5', ' 3.4', ' 1.5', ' 0.2'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1']], dtype='<U16')

In [116]:
irisHeader = np.array(["sepal length", "sepal width", "petal length", "petal width", "Species No"])


In [117]:
irisHeader

array(['sepal length', 'sepal width', 'petal length', 'petal width',
       'Species No'], dtype='<U12')

In [118]:
iris = iris.astype(float)
iris_max = iris.max(axis=1)
iris_max

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.5, 6.1, 5.8,
       5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.9, 6.7, 6.9, 5.8, 6.8, 6.7,
       6.7, 6.3, 6.5, 6.2])

In [119]:
iris_min = iris.min(axis=0)
iris_min

array([4.4, 2.3, 1.3, 0.1])

In [120]:
iris_avg = iris.mean(axis=0).round(3)
iris_avg

array([5.683, 3.027, 3.613, 1.217])

In [121]:
iris_standardDev = iris.std(axis=0).round(2)
iris_standardDev

array([0.76, 0.35, 1.65, 0.82])

In [122]:
iris1 = iris1.astype(float)
iris1_max = iris1.max(axis=1)
iris1_max


array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9])

In [123]:
iris2 = iris2.astype(float)
iris2_max = iris2.max(axis=1)
iris2_max

array([5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7])

In [124]:
iris3 = iris3.astype(float)
iris3_max = iris3.max(axis=1)
iris3_max

array([6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2])

In [125]:
iris1_min = iris1.min(axis=1)
iris1_min

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1])

In [126]:
iris2_min = iris2.min(axis=1)
iris2_min

array([1.2, 1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3])

In [127]:

iris3_min = iris3.min(axis=1)
iris3_min

array([5.8, 2.5, 5. , 1.9])

In [129]:
iris1_avg = iris1.mean(axis=1)
iris1_avg

array([2.55 , 2.375, 2.35 , 2.35 , 2.55 , 2.85 , 2.425, 2.525, 2.225,
       2.4  ])

In [130]:
iris2_avg = iris2.mean(axis=1)
iris2_avg


array([3.425, 3.775, 3.4  , 2.9  , 3.45 , 3.525, 3.525, 3.675, 2.925,
       3.475])

In [131]:
iris3_avg = iris3.mean(axis=1)
iris3_avg

array([6.55, 3.04, 5.36, 2.2 ])

In [134]:
iris1_standardDev = iris1.std(axis=0).round(2)
iris1_standardDev

array([0.28, 0.29, 0.1 , 0.07])

In [136]:
iris2_std = iris2.std(axis=0).round(2)
iris2_std


array([0.36, 0.22, 0.47, 0.11])

In [137]:
iris3_std = iris3.std(axis=0).round(2)
iris3_std


array([0.34, 0.25, 0.28, 0.2 ])

In [138]:
iris3_std = iris3.std(axis=0).round(2)
iris3_std

array([0.34, 0.25, 0.28, 0.2 ])

In [139]:
iris1_min[0] > iris_min[0]

np.False_

In [140]:
iris2_min[0] > iris_min[0]

np.False_

In [141]:
 iris3_min[0] > iris_min[0]

np.True_

In [142]:
 iris1_avg[1] > iris2_avg[1]

np.False_

In [143]:
iris1_avg[2] > iris2_avg[2]

np.False_

In [144]:
iris1_avg[3] > iris2_avg[3]

np.False_