<a href="https://colab.research.google.com/github/lakshman-reddy-sudo/Phoenixxx-Tv/blob/main/irisDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
iris = np.genfromtxt('iris2.txt', delimiter = ",", dtype=str)
iris

array([['5.1', ' 3.5', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.9', ' 3', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2', ' Iris-setosa', ' 1'],
       ['5', ' 3.6', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4', ' Iris-setosa', ' 1'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3', ' Iris-setosa', ' 1'],
       ['5', ' 3.4', ' 1.5', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2', ' Iris-setosa', ' 1'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1', ' Iris-setosa', ' 1'],
       ['5.5 ', ' 2.6', ' 4.4', ' 1.2', ' Iris-versicolor', ' 2'],
       ['6.1 ', ' 3', ' 4.6', ' 1.4', ' Iris-versicolor', ' 2'],
       ['5.8', ' 2.6', ' 4', ' 1.2', ' Iris-versicolor', ' 2'],
       ['5', ' 2.3', ' 3.3', ' 1', ' Iris-versicolor', ' 2'],
       ['5.6 ', ' 2.7', ' 4.2', ' 1.3', ' Iris-versicolor', ' 2'],
       ['5.7 ', ' 3', ' 4.2', ' 1.2', ' Iris-versicolor', ' 

In [ ]:
iris.shape

(30, 6)

In [ ]:
iris.ndim

2

In [ ]:
iris.size

180

In [ ]:
iris = iris[0:30,[0, 1, 2, 3,]]
iris

array([['5.1', ' 3.5', ' 1.4', ' 0.2'],
       ['4.9', ' 3', ' 1.4', ' 0.2'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2'],
       ['5', ' 3.6', ' 1.4', ' 0.2'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3'],
       ['5', ' 3.4', ' 1.5', ' 0.2'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1'],
       ['5.5 ', ' 2.6', ' 4.4', ' 1.2'],
       ['6.1 ', ' 3', ' 4.6', ' 1.4'],
       ['5.8', ' 2.6', ' 4', ' 1.2'],
       ['5', ' 2.3', ' 3.3', ' 1'],
       ['5.6 ', ' 2.7', ' 4.2', ' 1.3'],
       ['5.7 ', ' 3', ' 4.2', ' 1.2'],
       ['5.7', ' 2.9', ' 4.2', ' 1.3'],
       ['6.2 ', ' 2.9', ' 4.3', ' 1.3'],
       ['5.1', ' 2.5', ' 3', ' 1.1'],
       ['5.7', ' 2.8', ' 4.1', ' 1.3'],
       ['6.9', ' 3.1', ' 5.4', ' 2.1'],
       ['6.7', ' 3.1', ' 5.6', ' 2.4'],
       ['6.9', ' 3.1', ' 5.1', ' 2.3'],
       ['5.8', ' 2.7', ' 5.1', ' 1.9'],
       ['6.8', ' 3.2', ' 5.9', ' 2.3'],
       ['6.7

In [ ]:
iris1, iris2, iris3 = np.split(iris, [10,20], axis = 0)
iris

array([['5.1', ' 3.5', ' 1.4', ' 0.2'],
       ['4.9', ' 3', ' 1.4', ' 0.2'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2'],
       ['5', ' 3.6', ' 1.4', ' 0.2'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3'],
       ['5', ' 3.4', ' 1.5', ' 0.2'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1'],
       ['5.5 ', ' 2.6', ' 4.4', ' 1.2'],
       ['6.1 ', ' 3', ' 4.6', ' 1.4'],
       ['5.8', ' 2.6', ' 4', ' 1.2'],
       ['5', ' 2.3', ' 3.3', ' 1'],
       ['5.6 ', ' 2.7', ' 4.2', ' 1.3'],
       ['5.7 ', ' 3', ' 4.2', ' 1.2'],
       ['5.7', ' 2.9', ' 4.2', ' 1.3'],
       ['6.2 ', ' 2.9', ' 4.3', ' 1.3'],
       ['5.1', ' 2.5', ' 3', ' 1.1'],
       ['5.7', ' 2.8', ' 4.1', ' 1.3'],
       ['6.9', ' 3.1', ' 5.4', ' 2.1'],
       ['6.7', ' 3.1', ' 5.6', ' 2.4'],
       ['6.9', ' 3.1', ' 5.1', ' 2.3'],
       ['5.8', ' 2.7', ' 5.1', ' 1.9'],
       ['6.8', ' 3.2', ' 5.9', ' 2.3'],
       ['6.7

In [ ]:
iris1

array([['5.1', ' 3.5', ' 1.4', ' 0.2'],
       ['4.9', ' 3', ' 1.4', ' 0.2'],
       ['4.7', ' 3.2', ' 1.3', ' 0.2'],
       ['4.6', ' 3.1', ' 1.5', ' 0.2'],
       ['5', ' 3.6', ' 1.4', ' 0.2'],
       ['5.4 ', ' 3.9', ' 1.7', ' 0.4'],
       ['4.6', ' 3.4', ' 1.4', ' 0.3'],
       ['5', ' 3.4', ' 1.5', ' 0.2'],
       ['4.4', ' 2.9', ' 1.4', ' 0.2'],
       ['4.9', ' 3.1', ' 1.5', ' 0.1']], dtype='<U16')

In [ ]:
irisHeader = np.array(["sepal length", "sepal width", "petal length", "petal width", "Species No"])


In [ ]:
irisHeader

array(['sepal length', 'sepal width', 'petal length', 'petal width',
       'Species No'], dtype='<U12')

In [ ]:
iris = iris.astype(float)
iris_max = iris.max(axis=1)
iris_max

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.5, 6.1, 5.8,
       5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.9, 6.7, 6.9, 5.8, 6.8, 6.7,
       6.7, 6.3, 6.5, 6.2])

In [ ]:
iris_min = iris.min(axis=0)
iris_min

array([4.4, 2.3, 1.3, 0.1])

In [ ]:
iris_avg = iris.mean(axis=0).round(3)
iris_avg

array([5.683, 3.027, 3.613, 1.217])